### ISSUE TITLE
storage -> storage.ledger

### ISSUE THREAD

**Issue by ThomasLef** [completium/archetype-fa1#1]
https://github.com/completium/archetype-fa1/blob/feaec9bec11097a1097573c35d70675d902637fc/tests/utils.js#L8

Il me semble qu'il y a une erreur dans le getLedger, qui devrait aller chercher le storage.ledger et non pas juste le storage. Je ne sais pas si c'est lié à une différence d'environnement de ma part mais de mon côté il faut que je rajoute ce .ledger pour que ça fonctionne.

**Comment by guillaumeduhamel** [comment]
Dans cette version, il n'y a qu'un seul champ du storage. Donc en l'état, c'est bien `storage` et non pas `storage.ledger`. Si tu ajoutes un autre champ dans le contrat, alors oui ce sera `storage.ledger`, mais ici ce n'est pas le cas.
